[package]
name = "pazk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.3"
ark-std = "0.3"
ark-bls12-381 = "0.3"
ndarray = "0.15.4"
rand = "0.8.5"
