[package]
name = "pazk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.4.0"
ark-poly = "0.4.0"
ark-test-curves = { version = "0.4.0", features = ["bls12_381_curve", "bls12_381_scalar_field"] }
ndarray = "0.15.4"
rand = "0.8.5"
